name: Tracee Scan Example
on: [push]

jobs:
  example_job:
    runs-on: ubuntu-latest

    steps:
    - name: Start Tracee Pipeline Scan
      uses: simar7/tracee-action@master
#     uses: docker://simar7/golang-github-action:latest
#     uses: docker://simar7/golang-github-action:lite
      with:
        profile: start

    - name: Run strace
      run: |
        strace ls

    - name: Stop Tracee Pipeline Scan
      uses: simar7/tracee-action@master
      with:
        profile: stop
        fail-on-diff: true